apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: template-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: demo3.master.luka-j.rocks
    http:
      paths:
      - backend:
          service:
            name: template-service
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - demo3.master.luka-j.rocks
    secretName: template-tls-secret
